export const GET_MY_USER_DATA = "GET_MY_USER_DATA";

export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
export const CREATE_GLOBAL_ERROR = "CREATE_GLOBAL_ERROR";
export const RESET_GLOBAL_ERROR = "RESET_GLOBAL_ERROR";

export type ALERT_STATUS = "ERROR" | "SUCCESS" | "CONFIRM";
