export const GET_MY_USER_DATA = "GET_MY_USER_DATA";

export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
export const CREATE_GLOBAL_ERROR = "CREATE_GLOBAL_ERROR";
export const RESET_GLOBAL_ERROR = "RESET_GLOBAL_ERROR";


export const SET_BLOG_DATA = "SET_BLOG_DATA";
export const SET_PROJECTS_DATA = "SET_PROJECTS_DATA";

export type ALERT_STATUS = "ERROR" | "SUCCESS" | "CONFIRM";
